### ISSUE TITLE
ZERO runtime parachain test environment

### ISSUE THREAD

**Issue by 5-mark** [playzero/zero-network#203]
## User Story
As ZERO NETWORK we want to ensure that our parachain launch is tested with all the features to go live with when securing a slot so we can rely on the fact that a good quality goes live. 

## Tasks
- [ ] dev.node.zero.io --> for the environment delegated (define your own subdomain, if necessary)
- [ ] setup a test environment which mirrors the features (same feature set) which are planned to start the parachain with (ZERO RUNTIME)
- governance (council, tech commitee, what else?)
- staking, nomination, delegation etc (for network block rewards; incentive for collators)
- collator topic to be visualised and understood by chain team 
- collator election through staking by delegators
- staking payouts

- [ ] the test environment should be as near as possible to the future parachain prod environment state 
- [ ] initial token distribution #129  
- [ ] vesting should be simulated and tested
- [ ] determine fees and minimum deposits for participating (eg. become validator, apply for council etc)
- [ ] infaltion plan
- [ ] any burn mechanics?
- [ ] era, epoch, context, network role context (link configuration file)
- [ ] randomness function (to add contracts)
- [ ] locked tokens are available for staking and voting (utility but not possible to transfer/sell)

## How to test
1. simulate a parachain launch and token distribution + vesting 
2. find 8-10 stakeholders to run collators --> practice joining and leaving (etc) as collator on test env.
