### ISSUE TITLE
subzero prod environment (non tradable token)

### ISSUE THREAD

**Issue by 5-mark** [playzero/zero-network#204]
## Context

As GameDAO we want to have a stable & reliable environment which we use to mirror the guild case so that guild case can become a success.

## Tasks

- [ ] have a look on onfinality sessions
- [ ] have a production near environment like stage which  shall not to be resetted. 
- [ ] run SUBZERO runtime on it. 
- [ ] frequently update with features for the guild case 
- [ ] have current docker-images on dockerhub #task

## Additional Information
- this environment should not interfere with the normal staging environment (stage.gamedao.co) which can be queried for a faucet
- users of this environment will not be able to get tokens via the faucet but during an onboarding process by claiming tokens
- the claimed tokens are not related to the real parachain GAME/ZERO tokens but only are used on this platform for battlepass interactions.
