### ISSUE TITLE
sbp milestone I review

### ISSUE THREAD

**Issue by 2075** [playzero/zero-network#32]
wwe need to inform our friends at parity about our chain prior to the SBP Milestone review:

## 1. Documentation until June 14th @vovacha 
- [x] code documentation rephrased 
- [x] update readme files
- [x] code documentation created as web accessible markdown files
- [x] link to access the documentation pasted here - [https://docs.gamedao.co/gamedao-protocol/developer-documentation](https://docs.gamedao.co/gamedao-protocol/developer-documentation)

## 2. Code Links until June 14th @2075 

- Pallet Core:
[GameDAO Protocol](https://github.com/gamedaoco/gamedao-protocol)

- all pallets are in one location:
  - control — DAO core to create organizations with their segregated treasury and maintain members
  - signal — governance core to provide voting functionality with different outcomes and quora
  - flow — fundraising core to collect funds and move them to a DAO treasury upon success
  - sense — achievements and account based metrics
  - traits — overarching traits for the protocol pallets
  
- Build it with the zero runtime to get a working environment which you can test through polkadot.js.org/apps:
[ZERO Network](https://github.com/playzero/zero-network)

- you can also  run a local dev node via docker: 
``` docker run playzero/subzero:latest /usr/local/bin/subzero --dev --tmp --name hello-joy ```

## 3. How to test @vovacha 
- [x] perform the included test (this task is to write how this is done --> provide makefile which tests our own pallets in sbp/milestone-review-1) @vovacha
- to run tests: `make test`
- [x] provide instructions what to be done on the network (polkadot.js.org) @5-mark 
- https://docs.gamedao.co/guides/beeblebrox-testing

## 4. Architecture Documents @2075  
- [Documentation and user onboarding](https://docs.gamedao.co)
- [General Overview](https://www.figma.com/file/BpUtUShkRnhpALxE2JIG00/Overview?node-id=0%3A1)
- [Pallet Design](https://www.figma.com/file/b3O7FJ5F8gD84NzBsX2Vim/gamedao-protocol-%E2%80%94-pallet-design?node-id=0%3A1)
- [DAO Extrinsics](https://www.figma.com/file/QCHFHAxzUQxQxEMfBuMdnw/DAO-Extrinsics?node-id=2%3A2)
- [Campaign settlement](https://www.figma.com/file/Jqy2XnQh9ZgvU518Zhp48u/Scheduling-%2B-Campaign-Settlement?node-id=0%3A1)
- [Road to Parachain](https://www.figma.com/file/s9njA5FfYwP14wAAecEP3b/Road-to-Parachain-and-Protocol-Launch?node-id=0%3A1)

## 5. send out email @5-mark 
- [x] send out email with information until June 15th
