### ISSUE TITLE
parachain integration with other networks / XCMP

### ISSUE THREAD

**Issue by 2075** [playzero/zero-network#45]
# Overview
- https://www.figma.com/file/tCiZHNxH8s8010ZJlDwjWV/Parachain-Rococo?node-id=0%3A1
- https://www.figma.com/file/s9njA5FfYwP14wAAecEP3b/Road-to-Parachain-and-Protocol-Launch?node-id=0%3A1

# A. Chain
- [x] #46
- [x] #56
- [x] run parachain test setup
- [x] create chain-spec for rococo parachain
- [x] #33 

# B. Integrations
## 1.
- [ ] plan aUSD, ZERO, GAME testing
  - [x] #82 
  - [ ] #83 
  - [x] gamedaoco/gamedao-protocol/issues/96
- [ ] plan Kilt testing
  - [ ] Dudley / Kilt re DID integration

## 2.
- [x] runtime upgrade to feature
  - [x] #47
  - [x] #48

**Comment by 2075** [comment]
@vasylenko-yevhen @vovacha I guess we can update this?

**Comment by vasylenko-yevhen** [comment]
So all of the required parachain steps are complete.
For those integrations, which relate to 3rd parties or other parachains, I would suggest to work on them in separate scope and create additional tasks for this purpose. @2075 @5-mark wdyt?

**Comment by 2075** [comment]
@vasylenko-yevhen please proceed as discussed, playbook etc.
